[version("1.0.0"), FriendlyName("NICTeaming")] 
class NICTeaming : MSFT_BaseResourceConfiguration
{
  [Key] string Name;
  [write] string NICs;
  [write,ValueMap{"Switch Independent", "LACP", "Static Teaming"},Values{"Independent", "LACP", "Static"}] string Mode;
  [write,ValueMap{"Dynamic", "Hyper-V Port", "IP Addresses", "Mac Addresses", "Transport Ports"},Values{"Dynamic", "Hypervport", "IPAddresses", "MACAddresses", "TransportPorts"}] string LBMode;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write] string VlanID;
};
